### ISSUE TITLE
How to call plugin from C++ or swift application to feed the buffer

### ISSUE THREAD

**Issue by Raj123456788** [PhilippMatthes/neural-greenscreen#1]
trying to get an answer for this over a week now. Any guidance is appreciated.

**Comment by PhilippMatthes** [comment]
Please see the implementation of  neural-greenscreen/Interface/Virtual Camera/Stream.swift (Especially Lines 230+) for the relevant code on how to pipe image data (from Swift or C++, as you wish) into the pixelbuffer. Please look at https://github.com/seanchas116/SimpleDALPlugin for another example. If you have any further questions which are related to this project, hit me up again.

**Comment by Raj123456788** [comment]
Thanks. The plugin does not show up in quicktime player once added to the DAL folder.

**Comment by PhilippMatthes** [comment]
Try quitting the QuickTime Player with Cmd+Q and restarting it. Then it should show up.

**Comment by Raj123456788** [comment]
<img width="1272" alt="Screen Shot 2020-09-23 at 10 21 05 AM" src="https://user-images.githubusercontent.com/16295521/94047207-9ece8100-fd86-11ea-8450-6b5f66195ed3.png">
I have tried that  still no luck. I have also looked into https://github.com/seanchas116/SimpleDALPlugin. There is no application  that I can see how to send the buffer dataptr to the plugin.

**Comment by Raj123456788** [comment]
From the repo directory, run ./create-root-cert.sh and enter desired credentials for your signing certificate.
Ran this command but it does not generate the rootCA.pem I can only see rootCA.key
<img width="519" alt="Screen Shot 2020-09-23 at 10 31 32 AM" src="https://user-images.githubusercontent.com/16295521/94048211-03d6a680-fd88-11ea-82f7-71fd2b00b456.png">

**Comment by Raj123456788** [comment]
what changes I need to make the app in order to make it work with https://github.com/seanchas116/SimpleDALPlugin ? Atleast I can get started with that.

**Comment by Raj123456788** [comment]
got rootCA.pem working

**Comment by PhilippMatthes** [comment]
This seems to be a trial and error issue. To clarify this in advance: This repository is a fork of SimpleDALPlugin and may overlap with the functionalities and addresses used to create the plugin, which is why you probably only see one plugin and not both. It extends the basic functionalities of the example DAL plugin by image segmentation based background replacement. This is done by periodically fetching data from a node js app (after transferring the current camera image). For that to work one potentially needs an ssl certificate to communicate with the node js application (encrypted). That's what the ssl key generation is for.

To be fair, it took me a while to dig into the CoreMediaIO framework as well, because it is very complex. But I cannot tell you exactly which steps you need to take to achieve your goal, these steps you need to take yourself. For that, read the documentation carefully, maybe reach out for help on third party platforms such as stackoverflow, or look at the example code to catch the idea.

To be clear: I unfortunately cannot give you a detailed tutorial on how CoreMediaIO DAL works, that's on your part.

**Comment by Raj123456788** [comment]
No worries mate. Once I added the rootCA.pem to Key chain. I am not able to see it Keychain despite importing it. what name should I try to search in my certifictaes?

**Comment by Raj123456788** [comment]
you were right I removed simple DAL and your plugin appeared. But the background does not show up after yarn start since I have not trusted the cert as I cannot find it :) can you please help me locating it so that I get it working?

**Comment by Raj123456788** [comment]
got it working thanks!

**Comment by Raj123456788** [comment]
One last thing: The background still shows black although I have a different background.jpg in the root folder?

**Comment by Raj123456788** [comment]
Can you send me some documentation/links if possible?

**Comment by Raj123456788** [comment]
@PhilippMatthes Hi Philipp, I am trying to eliminate the video camera and just show the image. Tried commenting the video capture but that did not help.

**Comment by PhilippMatthes** [comment]
I locked this conversation since it is no longer related to the original issue. Please file another separate issue if there is anything more. Thanks!

**Comment by PhilippMatthes** [comment]
As a final hint, try to understand where the separate pixelbuffers are combined into one. Then start from there and select only one of the pixelbuffers.
